version: "3.9"

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: comments_app
      MYSQL_USER: nodeuser
      MYSQL_PASSWORD: 123456789!
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build: .
    container_name: comments-backend
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: nodeuser
      DB_PASSWORD: 123456789!
      DB_NAME: comments_app
      DB_DIALECT: mariadb
    ports:
      - "5000:5000"
    command: sh ./wait-for-db.sh

volumes:
  mariadb_data:
rm docker-compose.dev.yml
